[workspace]
members = [
    "cli-rs-macro",
    "playground",
]

[package]
name = "cli-rs"
version = "0.1.0"
description = "Type-safe command line parser"
authors = ["Kodai Matsumoto <nobita.0918@gmail.com>"]
repository = "https://github.com/0918nobita/cli-rs"
categories = ["command-line-interface"]
keywords = [
    "argument",
    "cli",
    "arg",
    "parser",
    "parse",
]
edition = "2021"
license = "MIT"
readme = "README.md"
include = [
    "src/**/*",
    "Cargo.toml",
    "Cargo.lock",
    "LICENSE",
    "README.md",
]

[dependencies]
cli-rs-macro = { path = "./cli-rs-macro" }
derive_more = "0.99.17"

[profile.release]
lto = true
codegen-units = 1
