[package]
name = "cli-rs"
version = "0.1.0"
authors = ["Kodai Matsumoto <nobita.0918@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
cli-rs-macro = { path = "../cli-rs-macro" }
thiserror = "1.0.30"
