[package]
name = "example-opts"
version = "0.1.0-alpha.0"
authors = ["Kodai Matsumoto <nobita.0918@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
cli-compose = { path = "../../", features = [ "schema" ] }
