[package]
name = "playground"
version = "0.1.0"
description = "Playground for testing cli-compose"
authors = ["Kodai Matsumoto <nobita.0918@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
cli-compose = { path = "../" }
